name=Scrollwheel
version=1.0.0
author=Silas Hörz
maintainer=Silas Hörz
sentence=A library to read capacitive radial slider and button data from the CY8CMBR3106S.
paragraph=This library provides an easy-to-use interface to extract raw data and gestures from the CY8CMBR3106S capacitive touch controller. It supports a 5-segment radial slider and a central touch button via I2C.
category=Sensors
url=https://github.com/Silas-Hoerz/Scrollwheel
architectures=*
depends=